import React from 'react';
import { ShoppingBag, Car, ShoppingCart, Gift, Plane, Home, BookOpen, Coffee } from 'lucide-react';

export const getIcon = (name: string) => {
    switch (name) {
        case 'ShoppingBag': return <ShoppingBag size={20} />;
        case 'Car': return <Car size={20} />;
        case 'ShoppingCart': return <ShoppingCart size={20} />;
        case 'Gift': return <Gift size={20} />;
        case 'Plane': return <Plane size={20} />;
        case 'Home': return <Home size={20} />;
        case 'BookOpen': return <BookOpen size={20} />;
        default: return <Coffee size={20} />;
    }
};

// List of available brands with cashback percentages
export const BRANDS_DATA = [
    // ALIMENTARI
    { name: 'Conad', percentage: 1.69, categories: ['alim'] },
    { name: 'Carrefour', percentage: 3.50, categories: ['alim'] },
    { name: 'Penny.', percentage: 3.38, categories: ['alim', 'md'] },
    { name: 'Bennet', percentage: 3.00, categories: ['alim'] },
    { name: 'ALI\'', percentage: 2.63, categories: ['alim'] },
    { name: 'Iper La grande i', percentage: 3.00, categories: ['alim'] },
    { name: 'Unes', percentage: 3.50, categories: ['alim'] },
    { name: 'Pam Panorama', percentage: 2.25, categories: ['alim'] },
    { name: 'Despar Nordest', percentage: 2.25, categories: ['alim'] },
    { name: 'Iperal', percentage: 2.25, categories: ['alim'] },
    { name: 'Mercatò', percentage: 2.25, categories: ['alim'] },
    { name: 'Unicomm', percentage: 2.25, categories: ['alim'] },
    { name: 'MAXI DI', percentage: 2.25, categories: ['alim'] },
    { name: 'Il Gigante', percentage: 4.75, categories: ['alim'] },
    { name: 'BASKO', percentage: 4.00, categories: ['alim'] },
    { name: 'Deco', percentage: 6.00, categories: ['alim'] },
    { name: 'SuperConveniente', percentage: 5.50, categories: ['alim'] },
    { name: 'Megamark', percentage: 4.00, categories: ['alim'] },
    { name: 'Martinelli Supermercati', percentage: 3.50, categories: ['alim'] },
    { name: 'Eataly', percentage: 3.38, categories: ['alim', 'regali'] },
    { name: 'Italmark', percentage: 3.50, categories: ['alim'] },
    { name: 'Migross', percentage: 3.00, categories: ['alim'] },
    { name: 'Iper Tosano', percentage: 4.00, categories: ['alim'] },
    { name: 'Rossetto', percentage: 3.75, categories: ['alim'] },
    { name: 'EKOM', percentage: 2.78, categories: ['alim', 'md'] },
    { name: 'MD', percentage: 3.00, categories: ['alim', 'md'] },
    { name: 'Todis', percentage: 1.88, categories: ['alim'] },
    { name: 'Eurospin', percentage: 1.00, categories: ['alim'] },


    // CARBURANTE
    { name: 'Tamoil', percentage: 2.50, categories: ['carb'] },
    { name: 'Q8', percentage: 2.50, categories: ['carb'] },
    { name: 'IP', percentage: 1.88, categories: ['carb'] },
    { name: 'Buono Enilive Digitale', percentage: 1.88, categories: ['carb'] },
    { name: 'Buono Enilive Servito Digitale', percentage: 2.25, categories: ['carb'] },

    // IGIENE PERSONAL
    { name: 'Tigotà', percentage: 4.13, categories: ['igiene', 'casa'] },
    { name: 'Acqua & Sapone', percentage: 5.00, categories: ['igiene', 'casa'] },
    { name: 'Douglas', percentage: 5.50, categories: ['igiene', 'regali'] },
    { name: 'Sephora', percentage: 4.13, categories: ['igiene', 'regali'] },
    { name: 'Marionnaud Paris', percentage: 4.87, categories: ['igiene', 'regali'] },
    { name: 'Bottega Verde', percentage: 3.38, categories: ['igiene', 'regali'] },
    { name: 'L\'ERBOLARIO', percentage: 3.00, categories: ['igiene', 'regali'] },
    { name: 'Rituals', percentage: 6.38, categories: ['igiene', 'regali'] },
    { name: 'EsserBella Profumerie', percentage: 3.75, categories: ['igiene', 'regali'] },

    // JOLLY (Valid for almost everything)
    { name: 'Amazon.it', percentage: 1.87, categories: ['alim', 'igiene', 'abb', 'regali', 'casa', 'school', 'md'] },
    { name: 'ideaShopping', percentage: 1.88, categories: ['alim', 'igiene', 'abb', 'regali', 'casa', 'school', 'md', 'treni'] },

    // TRASPORTI
    { name: 'Trenitalia', percentage: 3.38, categories: ['treni', 'regali'] },
    { name: 'Italo', percentage: 2.78, categories: ['treni', 'regali'] },
    { name: 'FlixBus', percentage: 5.00, categories: ['treni', 'regali'] },
    { name: 'ITA AIRWAYS', percentage: 3.38, categories: ['treni', 'regali'] },
    { name: 'UBER', percentage: 2.40, categories: ['treni'] },
    { name: 'Volagratis', percentage: 8.00, categories: ['treni', 'regali'] },
    { name: 'IBERIA LÍNEAS AÉREAS', percentage: 3.75, categories: ['treni'] },
    { name: 'Airbnb', percentage: 3.50, categories: ['treni', 'regali'] },
    { name: 'Booking.com', percentage: 3.00, categories: ['treni', 'regali'] },

    // ABBIGLIAMENTO
    { name: 'OVS', percentage: 7.50, categories: ['abb', 'regali'] },
    { name: 'Zalando', percentage: 8.00, categories: ['abb', 'regali'] },
    { name: 'H&M', percentage: 4.88, categories: ['abb', 'regali'] },
    { name: 'Primark', percentage: 3.75, categories: ['abb', 'regali'] },
    { name: 'Tezenis', percentage: 3.38, categories: ['abb', 'regali'] },
    { name: 'Terranova', percentage: 6.00, categories: ['abb', 'regali'] },
    { name: 'PittaRosso', percentage: 4.50, categories: ['abb', 'regali'] },
    { name: 'Intimissimi', percentage: 3.38, categories: ['abb', 'regali'] },
    { name: 'Scarpe&Scarpe', percentage: 2.63, categories: ['abb', 'regali'] },
    { name: 'Calzedonia', percentage: 3.38, categories: ['abb', 'regali'] },
    { name: 'Nike', percentage: 3.00, categories: ['abb', 'regali'] },
    { name: 'Guess', percentage: 4.13, categories: ['abb', 'regali'] },
    { name: 'Foot Locker', percentage: 7.50, categories: ['abb', 'regali'] },
    { name: 'Calliope', percentage: 5.00, categories: ['abb', 'regali'] },
    { name: 'Doppelganger', percentage: 4.88, categories: ['abb', 'regali'] },
    { name: 'Rinascimento', percentage: 5.50, categories: ['abb', 'regali'] },
    { name: 'Asos', percentage: 4.88, categories: ['abb', 'regali'] },
    { name: 'Falconeri', percentage: 4.88, categories: ['abb', 'regali'] },
    { name: 'Chicco', percentage: 4.88, categories: ['abb', 'regali', 'school'] },
    { name: 'Du Pareil Au Meme', percentage: 8.00, categories: ['abb', 'regali'] },
    { name: 'Coccinelle', percentage: 3.00, categories: ['abb', 'regali'] },
    { name: 'Ray-Ban', percentage: 4.13, categories: ['abb', 'regali'] },
    { name: 'Coin', percentage: 6.00, categories: ['abb', 'regali', 'casa'] },

    // ELETTRONICA & CASA & SCHOOL & REGALI (Misti)
    { name: 'MediaWorld', percentage: 2.50, categories: ['regali', 'casa', 'tech'] },
    { name: 'Unieuro', percentage: 3.00, categories: ['regali', 'casa', 'tech'] },
    { name: 'Trony', percentage: 1.65, categories: ['regali', 'casa', 'tech'] },
    { name: 'Expert', percentage: 1.88, categories: ['regali', 'casa', 'tech'] },
    { name: 'TOYS CENTER', percentage: 4.50, categories: ['regali', 'school'] },
    { name: 'Kasanova', percentage: 3.00, categories: ['casa', 'regali'] },
    { name: 'IKEA', percentage: 6.50, categories: ['casa', 'regali'] },
    { name: 'Brico Io', percentage: 4.00, categories: ['casa', 'regali'] },
    { name: 'Bricocenter', percentage: 2.62, categories: ['casa', 'regali'] },
    { name: 'Maisons du Monde', percentage: 7.50, categories: ['casa', 'regali'] },
    { name: 'Feltrinelli', percentage: 7.00, categories: ['school', 'regali', 'tech'] },
    { name: 'Mondadori Store', percentage: 4.13, categories: ['school', 'regali', 'tech'] },
    { name: 'Libraccio.it', percentage: 4.50, categories: ['school', 'regali'] },
    { name: 'Giunti al Punto', percentage: 4.13, categories: ['school', 'regali'] },
    { name: 'Hoepli.it', percentage: 4.88, categories: ['school', 'regali'] },
    { name: 'IBS.it', percentage: 4.50, categories: ['school', 'regali'] },
    { name: 'Decathlon', percentage: 4.13, categories: ['regali', 'abb'] },
    { name: 'Gamelife', percentage: 4.00, categories: ['regali', 'tech'] },
    { name: 'Google Play IT', percentage: 2.25, categories: ['regali', 'tech'] },
    { name: 'Grand Vision Italy', percentage: 4.50, categories: ['regali'] },
    { name: 'Signorvino', percentage: 4.13, categories: ['regali', 'alim'] },
    { name: 'QC SPA', percentage: 5.62, categories: ['regali'] },
    { name: 'Swarovski', percentage: 7.13, categories: ['regali'] },
    { name: 'Smartbox', percentage: 8.50, categories: ['regali'] },
    { name: 'Xbox', percentage: 10.50, categories: ['regali', 'tech'] },
    { name: 'Tannico.it', percentage: 4.88, categories: ['regali', 'alim'] },
    { name: 'GetYourGuide', percentage: 5.25, categories: ['regali', 'treni'] },
    { name: 'VISTASì', percentage: 4.13, categories: ['regali'] },
    { name: 'Global Hotel Card', percentage: 5.25, categories: ['regali', 'treni'] },
    { name: 'LEGO', percentage: 4.13, categories: ['regali'] },
    { name: 'Boscolo', percentage: 12.38, categories: ['regali', 'treni'] },
    { name: 'Interflora', percentage: 8.50, categories: ['regali'] },
    { name: 'XBOX Live', percentage: 5.63, categories: ['regali', 'tech'] },
    { name: 'DAZN FULL', percentage: 3.38, categories: ['regali'] },
    { name: 'Lastminute', percentage: 7.00, categories: ['regali', 'treni'] },
    { name: 'Piquadro.com', percentage: 8.63, categories: ['regali', 'abb'] },
    { name: 'AS Roma', percentage: 3.75, categories: ['regali', 'abb'] },
    { name: 'Best Western Hotels & Resorts', percentage: 4.13, categories: ['regali', 'treni'] },
    { name: 'DisneyPlus Premium', percentage: 2.63, categories: ['regali'] },
    { name: 'Global Experiences Card', percentage: 5.25, categories: ['regali'] },
    { name: 'Abbonamenti.it', percentage: 5.63, categories: ['regali'] },
    { name: 'Venchi', percentage: 4.13, categories: ['regali', 'alim'] },
    { name: 'WeRoad', percentage: 5.63, categories: ['regali', 'treni'] },
    { name: 'Hotelgift', percentage: 7.00, categories: ['regali', 'treni'] },
    { name: 'Twitch', percentage: 2.25, categories: ['regali', 'tech'] },
    { name: 'Winelivery', percentage: 3.00, categories: ['regali', 'alim'] },
    { name: 'Ecobnb', percentage: 4.13, categories: ['regali', 'treni', 'casa'] },
    { name: 'Flightgift', percentage: 4.00, categories: ['regali', 'treni'] },
    { name: 'Salute Semplice', percentage: 7.88, categories: ['regali', 'igiene'] },
    { name: 'Activitygift', percentage: 7.00, categories: ['regali'] },
    { name: 'FAO Schwarz', percentage: 6.50, categories: ['regali'] },
    { name: 'HotelsGift', percentage: 6.00, categories: ['regali', 'treni'] },
    { name: 'I primi 3 mesi di Sky TV + Sky Calcio + Sky Sport', percentage: 3.38, categories: ['regali'] },
    { name: 'I primi 3 mesi di Sky TV e Netflix (Intrattenimento plus) + Sky Cinema', percentage: 3.38, categories: ['regali'] },
    { name: 'UTravel', percentage: 5.25, categories: ['regali', 'treni'] },
    { name: 'Zoologos', percentage: 7.00, categories: ['regali', 'casa'] },

    // ESEMPIO AFFILIAZIONI INTERNET
    { name: 'AliExpress', percentage: 6.92, categories: ['aff_int'] },
    { name: 'SHEIN', percentage: 25.00, categories: ['aff_int'] },
    { name: 'Nespresso', percentage: 7.00, categories: ['aff_int'] },
    { name: 'Folletto', percentage: 6.00, categories: ['aff_int'] },
    { name: 'Avon', percentage: 7.00, categories: ['aff_int'] },
    { name: 'Nord Vpn', percentage: 40.00, categories: ['aff_int'] },
    { name: 'Panda security', percentage: 35.00, categories: ['aff_int'] },
    { name: 'Thun', percentage: 8.00, categories: ['aff_int'] },
    { name: 'Kaspersky', percentage: 5.00, categories: ['aff_int'] },
    { name: 'Wondershare', percentage: 30.00, categories: ['aff_int'] },
    { name: 'Axa', percentage: 12.00, categories: ['aff_int'] },
    { name: 'Veratour', percentage: 0, fixedAmount: 21, categories: ['aff_int'] },
    { name: 'Babbel', percentage: 0, fixedAmount: 60, categories: ['aff_int'] },
    { name: 'VERY MOBILE', percentage: 0, fixedAmount: 15, categories: ['aff_int'] },
    { name: 'Kena Mobile', percentage: 0, fixedAmount: 34, categories: ['aff_int'] },
    { name: 'Bidoo', percentage: 0, fixedAmount: 5, categories: ['aff_int'] },
    { name: 'Uni salute', percentage: 0, fixedAmount: 26.93, categories: ['aff_int'] },
    { name: 'La Stampa', percentage: 0, fixedAmount: 12, categories: ['aff_int'] },
    { name: 'La Repubblica', percentage: 0, fixedAmount: 12, categories: ['aff_int'] },
    { name: 'Allianz Assicurazioni', percentage: 0, fixedAmount: 13, categories: ['aff_int'] },
    { name: 'Telepass', percentage: 0, fixedAmount: 25, categories: ['aff_int'] },
    { name: 'Ho Mobile', percentage: 0, fixedAmount: 11, categories: ['aff_int'] },
    { name: 'Lyca Mobile', percentage: 0, fixedAmount: 5, categories: ['aff_int'] }
,
    { name: 'Iper', percentage: 5.00, categories: ['alim', 'carb'] },
    { name: 'MyGiftCardSquare', percentage: 1.75, categories: ['regali'] },
    { name: 'Arcaplanet', percentage: 3.50, categories: ['regali'] },
    { name: 'TIGROS', percentage: 3.50, categories: ['alim'] },
    { name: 'Pewex', percentage: 4.00, categories: ['alim'] },
    { name: 'NaturaSi', percentage: 3.75, categories: ['alim'] },
    { name: 'MyGiftCardSquare First', percentage: 2.50, categories: ['regali'] },
    { name: 'Salmoiraghi & Vigano\'', percentage: 4.13, categories: ['regali'] },
    { name: 'Deliveroo', percentage: 3.50, categories: ['regali'] },
    { name: 'PlayStation', percentage: 7.50, categories: ['regali'] },
    { name: 'TheFork', percentage: 5.00, categories: ['regali'] },
    { name: 'Roadhouse', percentage: 7.50, categories: ['regali'] },
    { name: 'Pim', percentage: 3.75, categories: ['regali'] },
    { name: 'ENI', percentage: 2.50, categories: ['carb'] },
    { name: 'Elite Supermercati', percentage: 3.50, categories: ['alim'] },
    { name: 'Roblox', percentage: 8.00, categories: ['regali'] },
    { name: 'Supermercati Dem', percentage: 3.00, categories: ['alim'] },
    { name: 'United Colors of Benetton', percentage: 3.75, categories: ['abb'] },
    { name: 'API IP', percentage: 2.50, categories: ['carb'] },
    { name: 'Nau', percentage: 7.00, categories: ['regali'] },
    { name: 'Bata', percentage: 4.00, categories: ['abb'] },
    { name: 'AW LAB', percentage: 4.00, categories: ['abb'] },
    { name: 'Nintendo eShop', percentage: 8.00, categories: ['regali'] },
    { name: 'Kiabi', percentage: 3.38, categories: ['abb'] },
    { name: 'UPIM', percentage: 3.38, categories: ['abb'] },
    { name: 'Snowit', percentage: 6.00, categories: ['regali'] },
    { name: 'CTS Supermercati', percentage: 3.00, categories: ['alim'] },
    { name: 'Miriade', percentage: 12.00, categories: ['abb'] },
    { name: 'Alpitour', percentage: 12.00, categories: ['regali'] },
    { name: 'Profumeria Ideale', percentage: 10.00, categories: ['igiene'] },
    { name: 'Toys', percentage: 6.00, categories: ['regali'] },
    { name: 'Bimbostore', percentage: 6.00, categories: ['regali'] },
    { name: 'Yeppon', percentage: 3.50, categories: ['tech'] },
    { name: '3Bee', percentage: 16.00, categories: ['regali'] },
    { name: 'Academia', percentage: 17.00, categories: ['alim', 'school'] },
    { name: 'Carriereit', percentage: 29.00, categories: ['regali'] },
    { name: 'Cerox', percentage: 12.00, categories: ['regali'] },
    { name: 'Dietetic', percentage: 13.00, categories: ['regali'] },
    { name: 'Nintendo Switch Online', percentage: 10.00, categories: ['regali'] },
    { name: 'Panarello', percentage: 12.00, categories: ['regali'] },
    { name: 'Abbonamenti', percentage: 8.00, categories: ['regali'] },
    { name: 'Almasicily', percentage: 13.00, categories: ['regali'] },
    { name: 'Bitdefender', percentage: 30.00, categories: ['regali'] },
    { name: 'Borbonese', percentage: 10.00, categories: ['abb'] },
    { name: 'British School', percentage: 13.00, categories: ['school'] },
    { name: 'BTX Bar', percentage: 12.00, categories: ['regali'] },
    { name: 'Caffe Borbone', percentage: 10.00, categories: ['regali'] },
    { name: 'Casa Folino 1962', percentage: 10.00, categories: ['regali'] },
    { name: 'CC Fuentes', percentage: 2.50, categories: ['regali'] },
    { name: 'Cilento Outlet', percentage: 2.00, categories: ['regali'] },
    { name: 'CityLife Shopping District', percentage: 2.00, categories: ['regali'] },
    { name: 'ClinGo', percentage: 12.00, categories: ['regali'] },
    { name: 'doc Supermercati', percentage: 3.00, categories: ['alim'] },
    { name: 'DoFit', percentage: 12.00, categories: ['regali'] },
    { name: 'Dr Beckmann', percentage: 13.00, categories: ['regali'] },
    { name: 'Eathlon', percentage: 15.00, categories: ['regali'] },
    { name: 'EquoTube', percentage: 12.00, categories: ['regali'] },
    { name: 'Fever Candlelight', percentage: 8.00, categories: ['regali'] },
    { name: 'Fiorentini', percentage: 10.00, categories: ['regali'] },
    { name: 'Fitness da Divano', percentage: 13.00, categories: ['regali'] },
    { name: 'Fitness da Scrivania', percentage: 13.00, categories: ['regali'] },
    { name: 'Franciacorta Village', percentage: 2.00, categories: ['regali'] },
    { name: 'Gioielli Dop', percentage: 12.00, categories: ['regali'] },
    { name: 'Hawaii Moka', percentage: 12.00, categories: ['regali'] },
    { name: 'IBS', percentage: 6.00, categories: ['school'] },
    { name: 'Il Viaggiator Goloso', percentage: 2.50, categories: ['alim'] },
    { name: 'Io sono te', percentage: 8.00, categories: ['regali'] },
    { name: 'Japal', percentage: 12.00, categories: ['regali'] },
    { name: 'Kimbo', percentage: 10.00, categories: ['regali'] },
    { name: 'Le Conserve della Nonna', percentage: 12.00, categories: ['abb'] },
    { name: 'Libraccio', percentage: 6.00, categories: ['school'] },
    { name: 'Luxury Zone', percentage: 4.00, categories: ['abb'] },
    { name: 'Mantova Village', percentage: 2.00, categories: ['regali'] },
    { name: 'Microsoft 365', percentage: 13.00, categories: ['school'] },
    { name: 'Mister Magic', percentage: 12.00, categories: ['casa', 'abb'] },
    { name: 'MyGiftBox Experience', percentage: 19.00, categories: ['regali'] },
    { name: 'Old Wild West', percentage: 3.00, categories: ['regali'] },
    { name: 'Orphea', percentage: 12.00, categories: ['regali'] },
    { name: 'Palmanova Village', percentage: 2.00, categories: ['regali'] },
    { name: 'Petti', percentage: 10.00, categories: ['regali'] },
    { name: 'Podovis', percentage: 12.00, categories: ['regali', 'abb'] },
    { name: 'Prenatal', percentage: 6.00, categories: ['regali'] },
    { name: 'Puglia Village', percentage: 2.00, categories: ['regali'] },
    { name: 'San Carlo', percentage: 12.00, categories: ['regali'] },
    { name: 'Smart Tales', percentage: 26.00, categories: ['regali'] },
    { name: 'Storytel', percentage: 5.00, categories: ['regali'] },
    { name: 'Supermercati Piccolo', percentage: 3.00, categories: ['alim'] },
    { name: 'tomarket', percentage: 2.50, categories: ['alim'] },
    { name: 'Travelcard by Inspire', percentage: 5.00, categories: ['regali'] },
    { name: 'Tuti', percentage: 10.00, categories: ['regali'] },
    { name: 'Valdichiana Village', percentage: 2.00, categories: ['regali'] },
    { name: 'Valsoia', percentage: 12.00, categories: ['alim'] },
    { name: 'Vitavigor', percentage: 13.00, categories: ['regali'] },
    { name: 'Walber', percentage: 2.00, categories: ['alim'] },
    { name: 'Wallife', percentage: 12.00, categories: ['regali'] }
].sort((a, b) => a.name.localeCompare(b.name));
